services:
  - type: web
    runtime: node
    name: poeruum
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: checksPass
