import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(async () => {
    const { mountDirectoryHarness } = await import('/e2e/directory-harness.tsx')
    mountDirectoryHarness()
  })
})

test('finds products inside stores and restores the directory when cleared', async ({ page }) => {
  const input = page.getByRole('searchbox', { name: 'Otsi poode ja tooteid' })
  await expect(page.locator('.store-directory__card')).toHaveCount(2)
  await expect(page.locator('.store-directory__product')).toHaveCount(0)
  await input.fill('vaas')
  const product = page.getByRole('region', { name: 'Leitud tooted' })
  await expect(product.getByRole('heading', { name: 'Sinine vaas' })).toBeVisible()
  await expect(product.getByText('Keraamika Stuudio', { exact: true })).toBeVisible()
  await expect(product.getByText('24 €', { exact: true })).toBeVisible()
  await expect(product.locator('del')).toHaveText('30 €')
  await expect(product.getByRole('link')).toHaveAttribute('href', 'https://keraamika-stuudio.poeruum.ee/toode/sinine-vaas/?from=kaubamaja')
  await expect(page.locator('.store-directory__card')).toHaveCount(0)
  await expect(page.getByRole('status')).toHaveText('1 toode, 0 poodi.')
  await input.press('Enter')
  await expect(input).toHaveValue('vaas')
  await expect(page).toHaveURL(/\?q=vaas$/)
  await page.getByRole('button', { name: 'Tühjenda otsing' }).click()
  await expect(input).toBeFocused()
  await expect(page.locator('.store-directory__card')).toHaveCount(2)
  await expect(page.locator('.store-directory__product')).toHaveCount(0)
  expect(new URL(page.url()).searchParams.has('q')).toBe(false)
})

test('finds store names and descriptions, handles accents, and uses custom product domains', async ({ page }) => {
  const input = page.getByRole('searchbox')
  await input.fill('savist')
  await expect(page.locator('.store-directory__card')).toHaveCount(1)
  await expect(page.locator('.store-directory__card h3')).toHaveText('Keraamika Stuudio')
  await input.fill('POHJALA')
  await expect(page.getByRole('region', { name: 'Leitud poed' }).getByRole('heading')).toHaveText('Põhjala Puit')
  await expect(page.locator('.store-directory__product')).toHaveCount(1)
  await input.fill('pohjala loikelaud')
  const product = page.locator('.store-directory__product')
  await expect(product.getByRole('link')).toHaveAttribute('href', 'https://puit.example.ee/toode/loikelaud/?from=kaubamaja')
  await expect(product.getByText('Välja müüdud')).toBeVisible()
  await input.fill('köögitarvik')
  await expect(product.getByRole('heading')).toHaveText('Lõikelaud')
  await input.fill('jalgratas')
  await expect(page.getByText('Vasteid ei leitud. Proovi teist märksõna.')).toBeVisible()
  await expect(product).toHaveCount(0)
  await input.press('Escape')
  await expect(page.locator('.store-directory__card')).toHaveCount(2)
})

test('search remains usable on mobile and restores queries from the URL', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(async () => {
    window.history.replaceState({}, '', '/?q=loikelaud')
    const { mountDirectoryHarness } = await import('/e2e/directory-harness.tsx')
    mountDirectoryHarness()
  })
  const input = page.getByRole('searchbox')
  await expect(input).toHaveValue('loikelaud')
  await expect(page.locator('.store-directory__product h3')).toHaveText('Lõikelaud')
  await input.scrollIntoViewIfNeeded()
  await expect(input).toBeInViewport()
  const clear = page.getByRole('button', { name: 'Tühjenda otsing' })
  await expect(clear).toBeInViewport()
  expect((await clear.boundingBox())?.width).toBeGreaterThanOrEqual(44)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await clear.click()
  await expect(page.locator('.store-directory__card')).toHaveCount(2)
})

test('shows additional matches and resets the result limit for a new search', async ({ page }) => {
  await page.evaluate(async () => {
    const { mountDirectoryHarness } = await import('/e2e/directory-harness.tsx')
    mountDirectoryHarness(true)
  })
  const input = page.getByRole('searchbox')
  await input.fill('kauss')
  await expect(page.locator('.store-directory__product')).toHaveCount(24)
  await page.getByRole('button', { name: 'Näita veel tooteid' }).click()
  await expect(page.locator('.store-directory__product')).toHaveCount(25)
  await expect(page.getByRole('button', { name: 'Näita veel tooteid' })).toHaveCount(0)
  await input.fill('vaas')
  await expect(page.locator('.store-directory__product')).toHaveCount(1)
  await input.fill('kauss')
  await expect(page.locator('.store-directory__product')).toHaveCount(24)
})
